apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bckapilistenerkc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bckapilistenerkc
    spec:
      containers:
      - name: bckapilistenerkc
        image: acrsatrack.azurecr.io/backend_listener_keycloack:1931
        ports:
        - containerPort: 80
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
      imagePullSecrets:
      - name: registrosatrack
      
---
apiVersion: v1
kind: Service
metadata:
  name: bckapilistenerkc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "SubnetKuber"
  labels:
    run: bckapilistenerkc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bckapilistenerkc
