apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bckapilistener
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bckapilistener
    spec:
      containers:
      - name: bckapilistener
        image: acrsatrack.azurecr.io/backend_listener:1.1.1
        ports:
        - containerPort: 80
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
      imagePullSecrets:
      - name: registrosatrack
      
---
apiVersion: v1
kind: Service
metadata:
  name: bckapilistener
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "SubnetKuber"
  labels:
    run: bckapilistener
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bckapilistener
