apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bckchangestatus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bckchangestatus
    spec:
      containers:
      - name: bckchangestatus
        image: acrsatrack.azurecr.io/backend_changestatus:1.1.2
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
            memory: 300Mi
      imagePullSecrets:
      - name: registrosatrack
