

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bckchagestatusnotification
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bckchagestatusnotification
    spec:
      containers:
      - name: bckchagestatusnotification
        image: acrsatrack.azurecr.io/backend_changestatus_notification:1.1.2
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
            memory: 300Mi
      imagePullSecrets:
      - name: registrosatrack
