apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bckchangestatus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bckchangestatus
    spec:
      containers:
      - name: bckchangestatus
        image: acrsatrack.azurecr.io/backend_services_changestatus:1.1.0
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          requests:
            cpu: 150m
          limits:
            cpu: 200m		
      imagePullSecrets:
      - name: registrosatrack
