apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bcktmractivation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bcktmractivation
    spec:
      containers:
      - name: bcktmractivation
        image: acrsatrack.azurecr.io/backend_activation:1.1.2
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
            memory: 400Mi
      imagePullSecrets:
      - name: registrosatrack
