apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: changestatus
  namespace: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: changestatus
    spec:
      containers:
      - name: changestatus
        image: acrsatrack.azurecr.io/backend_changestatus:6005
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
            memory: 300Mi
      imagePullSecrets:
      - name: registrosatrack
