apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bckapilistener
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bckapilistener
    spec:
      containers:
      - name: bckapilistener
        image: acrsatrack.azurecr.io/backend_listener:1.1.0
        ports:
        - containerPort: 80
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
      imagePullSecrets:
      - name: registrosatrack
      
---
apiVersion: v1
kind: Service
metadata:
  name: bckapilistener
  labels:
    run: bckapilistener
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  selector:
    app: bckapilistener
---
kind: Endpoints
apiVersion: v1
metadata:
  name: bckapilistener
subsets:
  - addresses:
      - ip: 10.3.128.193
    ports:
      - port: 9376
